"""Hand-written eBay and Etsy copy for each piece, keyed by its _products filename.

Descriptions come from the site at build time; what lives here is what search on
each marketplace rewards: titles, Etsy tags, eBay item specifics, condition, and
any notes to read before listing. Add an entry when a new piece goes up.
"""

# key: (ebay_title, etsy_title, etsy_tags[13], ebay_specifics{}, ebay_condition, flags[])
COPY = {
"beistle-frankenstein": (
  "Vintage 1980 Beistle Jointed Frankenstein Die-Cut Halloween Decoration",
  "Vintage 1980 Beistle Jointed Frankenstein Die-Cut, Poseable Halloween Wall Decoration, Retro Monster Decor",
  ["beistle", "vintage halloween", "frankenstein", "jointed die cut", "halloween die cut", "1980s halloween",
   "retro halloween", "monster decor", "halloween wall art", "paper halloween", "beistle die cut",
   "halloween collector", "classic monster"],
  {"Brand": "Beistle", "Character": "Frankenstein", "Type": "Die-Cut", "Material": "Paper / Cardboard",
   "Decade": "1980s", "Year": "1980", "Features": "Jointed, Poseable"}, "Used", []),
"beistle-jack-o-lantern-man": (
  "Vintage 1960s Beistle Jointed Pumpkin Man Die-Cut Halloween Jack-O-Lantern",
  "Vintage 1960s Beistle Jointed Pumpkin Goblin Die-Cut, Mid-Century Halloween Jack-O'-Lantern Man Wall Decoration",
  ["beistle", "vintage halloween", "jointed die cut", "pumpkin man", "jack o lantern", "1960s halloween",
   "mid century", "halloween die cut", "pumpkin goblin", "paper halloween", "retro halloween",
   "halloween wall art", "beistle die cut"],
  {"Brand": "Beistle", "Character": "Jack-O-Lantern", "Type": "Die-Cut", "Material": "Paper / Chipboard",
   "Decade": "1960s", "Features": "Jointed, Poseable"}, "Used", []),
"beistle-vampire-skeleton": (
  "Vintage 1980s Beistle Vampire Skeleton Die-Cut Halloween Decoration Laminated",
  "Vintage 1980s Beistle Vampire Skeleton Die-Cut, Neon Halloween Wall Decoration, Retro 80s Spooky Decor",
  ["beistle", "vintage halloween", "vampire", "skeleton", "halloween die cut", "1980s halloween",
   "80s halloween", "neon halloween", "retro halloween", "paper halloween", "halloween wall art",
   "beistle die cut", "spooky decor"],
  {"Brand": "Beistle", "Character": "Vampire, Skeleton", "Type": "Die-Cut", "Material": "Paper / Cardboard",
   "Decade": "1980s"}, "Used", []),
"ben-cooper-pirate-mask": (
  "Vintage 1960s Ben Cooper Pirate Mask Zest Soap Premium Halloween Neon",
  "Vintage 1960s Ben Cooper Pirate Mask, Zest Soap Store Premium, Neon Halloween Costume Mask, Advertising Collectible",
  ["ben cooper", "vintage mask", "halloween mask", "pirate mask", "1960s halloween", "zest soap",
   "advertising premium", "neon mask", "vintage costume", "retro halloween", "halloween collector",
   "plastic mask", "vintage halloween"],
  {"Brand": "Ben Cooper", "Character": "Pirate", "Type": "Mask", "Material": "Plastic", "Decade": "1960s",
   "Features": "Advertising Premium (Zest)"}, "Used",
  ["The witch mask is its partner from the same Zest promotion. Consider listing the pair as one bundle too."]),
"ben-cooper-witch-mask": (
  "Vintage 1960s Ben Cooper Witch Mask Zest Soap Premium Halloween Neon",
  "Vintage 1960s Ben Cooper Witch Mask, Zest Soap Store Premium, Neon Halloween Costume Mask, Advertising Collectible",
  ["ben cooper", "vintage mask", "halloween mask", "witch mask", "1960s halloween", "zest soap",
   "advertising premium", "neon mask", "vintage costume", "retro halloween", "halloween collector",
   "plastic mask", "vintage halloween"],
  {"Brand": "Ben Cooper", "Character": "Witch", "Type": "Mask", "Material": "Plastic", "Decade": "1960s",
   "Features": "Advertising Premium (Zest)"}, "Used",
  ["The pirate mask is its partner from the same Zest promotion. Consider listing the pair as one bundle too."]),
"blinky-glowlight-pumpkin": (
  "Vintage Blinky Glow-Lite Jack-O-Lite Pumpkin Blow Mold Window Light in Box",
  "Vintage Blinky Glow-Lite Electric Jack-O-Lite, Flat Pumpkin Blow Mold Window Light in Original Box, Retro Halloween",
  ["blow mold", "vintage halloween", "blinky", "jack o lantern", "pumpkin light", "window light",
   "halloween light", "retro halloween", "1990s halloween", "glow lite", "pumpkin decor",
   "halloween window", "vintage pumpkin"],
  {"Brand": "Blinky", "Character": "Jack-O-Lantern", "Type": "Blow Mold Window Light", "Material": "Plastic",
   "Decade": "1990s", "Features": "Light-Up, Original Box"}, "Used", []),
"ceramic-haunted-house-luminary": (
  "JCPenney Ceramic Haunted House Halloween Luminary Candle Holder 11 in Box",
  "JCPenney Ceramic Haunted House Luminary, 11 Inch Halloween Candle Holder with Ghost and Bat, Original Box",
  ["haunted house", "halloween luminary", "ceramic house", "candle holder", "halloween ceramic",
   "jcpenney", "halloween decor", "spooky house", "halloween village", "ceramic halloween",
   "haunted mansion", "mantel decor", "halloween candle"],
  {"Brand": "JCPenney", "Theme": "Haunted House", "Type": "Luminary / Candle Holder", "Material": "Ceramic",
   "Decade": "2000s", "Features": "Original Box"}, "Used",
  ["ETSY_YEAR"]),
"creepy-cookies": (
  "Reader's Digest Creepy Cookies Book & 5 Halloween Cookie Cutters Set Complete",
  "Vintage Reader's Digest Creepy Cookies Recipe Book and Halloween Cookie Cutter Set, Complete with 5 Cutters",
  ["cookie cutters", "halloween baking", "creepy cookies", "readers digest", "halloween cookies",
   "vintage cookbook", "cookie cutter set", "bat cookie cutter", "witch cookies", "ghost cookies",
   "halloween kitchen", "1990s halloween", "halloween gift"],
  {"Brand": "Reader's Digest", "Type": "Cookie Cutter Set & Recipe Book", "Material": "Plastic, Paper",
   "Decade": "1990s", "Features": "Complete, Original Box"}, "Used", []),
"ghost-blowmold-lights": (
  "Vintage Ghost BOO Blow Mold Candle Lights Set of 2 Halloween Window Lights",
  "Vintage Ghost BOO Blow Mold Candle Lights, Set of 2, Lighted Halloween Window Candles, Retro Halloween Decor",
  ["blow mold", "ghost blow mold", "vintage halloween", "halloween candles", "window candle", "boo ghost",
   "halloween light", "retro halloween", "1990s halloween", "ghost decor", "halloween window",
   "lighted ghost", "plastic ghost"],
  {"Character": "Ghost", "Type": "Blow Mold Candle Light", "Material": "Plastic", "Decade": "1990s",
   "Features": "Light-Up, Set of 2"}, "Used", []),
"ghost-light": (
  "JCPenney Acrylic Ghost Light with Jack-O-Lantern Pails Halloween in Box",
  "JCPenney Lighted Acrylic Ghost with Jack-O'-Lantern Pails, Halloween Table Light in Original Box",
  ["ghost light", "halloween ghost", "lighted ghost", "acrylic ghost", "jcpenney", "halloween light",
   "jack o lantern", "halloween decor", "ghost decor", "table lamp", "halloween lamp", "spooky decor",
   "trick or treat"],
  {"Brand": "JCPenney", "Character": "Ghost", "Type": "Table Light", "Material": "Acrylic",
   "Decade": "2000s", "Features": "Light-Up, Original Box"}, "Used",
  ["ETSY_YEAR",
   "Your site's condition note mentions glaze and crazing, which reads as copied from the ceramic luminary. "
   "Acrylic has no glaze, so the copy here drops that line. Worth fixing on the site too."]),
"ghost-pumpkin-display": (
  "Holidays By Design Ghost & Pumpkin Halloween Tabletop Display Sealed NOS USA",
  "Vintage Holidays By Design Ghost and Pumpkin Tabletop Display, Sealed New Old Stock, Made in USA, Halloween Candy Dish",
  ["ghost decor", "pumpkin decor", "halloween display", "new old stock", "sealed vintage", "made in usa",
   "candy dish", "halloween candy", "tabletop decor", "mantel decor", "1990s halloween",
   "retro halloween", "halloween ghost"],
  {"Brand": "Holidays By Design", "Character": "Ghost, Jack-O-Lantern", "Type": "Tabletop Display",
   "Material": "Plastic", "Decade": "1990s", "Country/Region of Manufacture": "United States",
   "Features": "Sealed, New Old Stock"}, "New (sealed, never opened)", []),
"ghosty-guys": (
  "Vintage Artmark Ghosty Guys Halloween Night Light Ghosts Jack-O-Lantern 1980s",
  "Vintage 1980s Artmark Ghosty Guys Halloween Night Light, Ghosts and Jack-O'-Lantern Lighted Scene",
  ["night light", "halloween light", "ghost decor", "artmark", "1980s halloween", "vintage halloween",
   "jack o lantern", "lighted ghost", "retro halloween", "80s halloween", "halloween lamp", "ghost light",
   "spooky decor"],
  {"Brand": "Artmark", "Character": "Ghosts, Jack-O-Lantern", "Type": "Night Light", "Decade": "1980s",
   "Features": "Light-Up"}, "Used", []),
"hallmark-pumpkin": (
  "Hallmark Ceramic Jack-O-Lantern Color Changing LED Light Halloween in Box",
  "Hallmark Ceramic Jack-O'-Lantern with Color-Changing LED Base, Halloween Pumpkin Light in Original Box",
  ["hallmark", "jack o lantern", "ceramic pumpkin", "pumpkin light", "led pumpkin", "halloween light",
   "color changing", "halloween ceramic", "pumpkin decor", "halloween decor", "spider decor",
   "mantel decor", "halloween gift"],
  {"Brand": "Hallmark", "Character": "Jack-O-Lantern", "Type": "Light", "Material": "Ceramic",
   "Features": "Color-Changing LED, Original Box"}, "Used",
  ["Color-changing LED bases are more typical of the 2000s than the 1990s. Check the box for a date before "
   "listing it as vintage on Etsy, and before using the decade on eBay."]),
"haunted-house-cookie-jar": (
  "Vintage Sakura Halloween Haunted Hideaway House Ceramic Cookie Jar",
  "Vintage Sakura Haunted Hideaway House Ceramic Cookie Jar, Halloween Haunted House Kitchen Decor",
  ["cookie jar", "haunted house", "sakura", "ceramic cookie jar", "halloween kitchen", "vintage halloween",
   "halloween ceramic", "haunted mansion", "spooky kitchen", "halloween decor", "ceramic house",
   "kitchen decor", "halloween collector"],
  {"Brand": "Sakura", "Theme": "Haunted House", "Type": "Cookie Jar", "Material": "Ceramic",
   "Decade": "1980s"}, "Used", []),
"jack-o-lantern-top-hat": (
  "Vintage 1978 Pumpkin Man Top Hat Blow Mold Halloween Light 14 in Jack-O-Lantern",
  "Vintage 1978 Pumpkin Man Blow Mold in Top Hat, 14 Inch Lighted Jack-O'-Lantern, Retro Halloween Decor",
  ["blow mold", "vintage blow mold", "pumpkin man", "jack o lantern", "halloween blow mold",
   "1970s halloween", "top hat", "lighted pumpkin", "retro halloween", "halloween light", "pumpkin decor",
   "vintage halloween", "porch decor"],
  {"Character": "Pumpkin Man", "Type": "Blow Mold", "Material": "Plastic", "Decade": "1970s", "Year": "1978",
   "Features": "Light-Up, LED Bulb"}, "Used", []),
"monster-mash-book": (
  "Blue Ridge Designs Monster Mash Animated Musical Book Halloween Lights Box",
  "Vintage Monster Mash Animated Musical Spellbook by Blue Ridge Designs, Lights and Sound, Original Box",
  ["monster mash", "animated halloween", "musical book", "blue ridge designs", "halloween animated",
   "spell book", "halloween music", "light up book", "1990s halloween", "vintage halloween",
   "retro halloween", "halloween decor", "haunted book"],
  {"Brand": "Blue Ridge Designs", "Theme": "Monster Mash", "Type": "Animated Musical Book", "Decade": "1990s",
   "Features": "Animated, Lights, Sound, Original Box"}, "Used", []),
"pete-the-ghost": (
  "Hallmark Pete the Ghost Glow in the Dark Window Cling 1990 Boo Bazaar Sealed",
  "Vintage 1990 Hallmark Pete the Ghost Glow-in-the-Dark Window Cling, Boo Bazaar, Sealed on Card",
  ["hallmark", "window cling", "glow in the dark", "ghost decor", "boo bazaar", "1990s halloween",
   "vintage halloween", "halloween window", "sealed vintage", "new old stock", "friendly ghost",
   "retro halloween", "halloween decal"],
  {"Brand": "Hallmark", "Character": "Pete the Ghost", "Type": "Window Cling", "Decade": "1990s",
   "Year": "1990", "Features": "Glow in the Dark, Sealed"}, "New (sealed on original card)", []),
"pumpkin-bumpkins": (
  "Halloween Works Pumpkin Bumpkins Scarecrow Costume Kit for Pumpkins in Box",
  "Halloween Works Pumpkin Bumpkins Scarecrow Costume Kit for Pumpkins, Complete in Original Box",
  ["pumpkin costume", "scarecrow", "pumpkin decor", "halloween works", "pumpkin kit", "fall decor",
   "porch decor", "pumpkin carving", "halloween decor", "harvest decor", "autumn decor",
   "pumpkin dress up", "halloween craft"],
  {"Brand": "Halloween Works", "Character": "Scarecrow", "Type": "Pumpkin Costume Kit", "Decade": "2000s",
   "Features": "Complete, Original Box"}, "Used",
  ["ETSY_YEAR",
   "At $8, marketplace fees and postage leave almost nothing. It may do better as a free add-on, part of a "
   "bundle, or local pickup."]),
"pumpkin-die-cut": (
  "Vintage 1940s Embossed Jack-O-Lantern Die-Cut Halloween Wall Decoration",
  "Vintage 1940s Embossed Jack-O'-Lantern Die-Cut, Mid-Century Halloween Paper Decoration, Crescent Moon Eyes",
  ["vintage die cut", "jack o lantern", "embossed die cut", "1940s halloween", "mid century",
   "paper halloween", "halloween die cut", "antique halloween", "pumpkin die cut", "halloween wall art",
   "halloween collector", "retro halloween", "vintage pumpkin"],
  {"Character": "Jack-O-Lantern", "Type": "Die-Cut", "Material": "Embossed Paper", "Decade": "1940s"}, "Used",
  ["Beistle and Luhrs are left out of the titles on purpose. eBay treats a brand name you can't confirm as "
   "keyword spam. The description keeps your 'possibly H.E. Luhrs or Beistle' wording, which is fine."]),
"relpo-pumpkin-planter": (
  "Vintage 1966 Relpo Ceramic Lighted Jack-O-Lantern #5375 Samson Import Label",
  "Vintage 1966 Relpo Ceramic Jack-O'-Lantern Light #5375, Samson Import with Original Foil Label, Mid-Century Halloween",
  ["relpo", "vintage ceramic", "jack o lantern", "ceramic pumpkin", "1960s halloween", "mid century",
   "samson import", "pumpkin light", "halloween ceramic", "lighted pumpkin", "halloween collector",
   "vintage pumpkin", "retro halloween"],
  {"Brand": "Relpo (Samson Import)", "Character": "Jack-O-Lantern", "Type": "Light", "Material": "Ceramic",
   "Decade": "1960s", "Year": "1966", "Model": "5375", "Features": "Light-Up, Original Foil Label"}, "Used", []),
"sonic-flying-vampire": (
  "Vintage 1980s Sonic Flying Vampire 24 in Sound Activated Halloween Decor Box",
  "Vintage 1980s Sonic Flying Vampire, 24 Inch Sound-Activated Hanging Halloween Decoration, Glowing Eyes, Original Box",
  ["vintage halloween", "vampire", "sound activated", "animated halloween", "hanging decor", "dracula",
   "1980s halloween", "80s halloween", "retro halloween", "halloween prop", "glowing eyes",
   "halloween decor", "haunted house"],
  {"Character": "Vampire", "Type": "Hanging Decoration", "Decade": "1980s",
   "Features": "Sound-Activated, Light-Up Eyes, Original Box"}, "Used", []),
"spooky-tree": (
  "Hallmark Spooky Tree Animated Musical Addams Family Theme Owls Lights Tag",
  "Hallmark Spooky Tree, Animated Musical Halloween Decoration, Plays the Addams Family Theme, Bobbing Owls",
  ["hallmark", "animated halloween", "spooky tree", "addams family", "musical decor", "halloween tree",
   "owl decor", "light up tree", "halloween decor", "haunted tree", "mantel decor", "halloween music",
   "spooky decor"],
  {"Brand": "Hallmark", "Theme": "Haunted Tree", "Type": "Animated Musical Decoration", "Decade": "2000s",
   "Features": "Animated, Lights, Sound, Original Tag"}, "Used",
  ["ETSY_YEAR"]),
"trendmasters-pumpkin-1993": (
  "Vintage 1993 Trendmasters Light Up Foam Jack-O-Lantern Pumpkin Halloween",
  "Vintage 1993 Trendmasters Light-Up Foam Jack-O'-Lantern, Lighted Halloween Pumpkin, Retro 90s Decor",
  ["trendmasters", "foam pumpkin", "jack o lantern", "light up pumpkin", "1990s halloween",
   "90s halloween", "vintage halloween", "lighted pumpkin", "halloween light", "retro halloween",
   "pumpkin decor", "porch decor", "halloween window"],
  {"Brand": "Trendmasters", "Character": "Jack-O-Lantern", "Type": "Light", "Material": "Foam",
   "Decade": "1990s", "Year": "1993", "Features": "Light-Up"}, "Used",
  ["The 1995 Trendmasters pumpkin would pair well with this one. A two-pumpkin bundle is worth trying."]),
"trendmasters-pumpkin-1995": (
  "Vintage 1995 Trendmasters Light Up Foam Jack-O-Lantern Pumpkin Halloween",
  "Vintage 1995 Trendmasters Light-Up Foam Jack-O'-Lantern, Lighted Halloween Pumpkin, Retro 90s Decor",
  ["trendmasters", "foam pumpkin", "jack o lantern", "light up pumpkin", "1990s halloween",
   "90s halloween", "vintage halloween", "lighted pumpkin", "halloween light", "retro halloween",
   "pumpkin decor", "porch decor", "halloween window"],
  {"Brand": "Trendmasters", "Character": "Jack-O-Lantern", "Type": "Light", "Material": "Foam",
   "Decade": "1990s", "Year": "1995", "Features": "Light-Up"}, "Used",
  ["The 1993 Trendmasters pumpkin would pair well with this one. A two-pumpkin bundle is worth trying."]),
"wolfman-costume": (
  "Vintage 1980 Collegeville Universal Monsters Wolfman Costume Mask Box Eckerd",
  "Vintage 1980 Collegeville Universal Monsters Wolfman Halloween Costume with Mask and Original Box, Child Small",
  ["collegeville", "universal monsters", "wolfman", "vintage costume", "halloween costume",
   "1980s halloween", "vintage mask", "wolf man", "monster costume", "retro halloween", "boxed costume",
   "halloween collector", "kids costume"],
  {"Brand": "Collegeville", "Character": "Wolfman (Universal Monsters)", "Type": "Costume with Mask",
   "Material": "Rayon, Vinyl", "Size": "Child Small (4-6)", "Decade": "1980s", "Year": "1980",
   "Features": "Original Box"}, "Used", []),
}

ETSY_YEAR = ("Etsy only accepts vintage made in 2006 or earlier. This one is marked 2000s, so confirm the year "
             "first. If it's newer, list it on eBay only.")
